# ══════════════════════════════════════════════════════════════════════════
# streamlit_gradboost_app.py
# Run with:  streamlit run streamlit_gradboost_app.py
# Requires:  gradboost_bundle.pkl  (generated by export_gradboost_pkl.py)
# ══════════════════════════════════════════════════════════════════════════

import pickle
import numpy as np
import pandas as pd
import streamlit as st
from sklearn.base import BaseEstimator, TransformerMixin

# ══════════════════════════════════════════════════════════════════════════
# LogColumnScaler — MUST be defined identically to the one used when the
# bundle was pickled (export_gradboost_pkl.py), or pickle.load() below will
# fail / silently misbehave.
# ══════════════════════════════════════════════════════════════════════════
_EPS = 1e-300


class LogColumnScaler(BaseEstimator, TransformerMixin):
    def __init__(self, columns, log_columns=None):
        self.columns = columns
        self.log_columns = log_columns

    def fit(self, X, y=None):
        X = np.asarray(X, dtype=float)
        columns = list(self.columns)
        log_columns = list(self.log_columns) if self.log_columns is not None else []
        self.log_mask_ = np.array([c in log_columns for c in columns])

        Xt = self._forward_log(X)
        self.mean_ = Xt.mean(axis=0)
        self.std_ = Xt.std(axis=0)
        self.std_[self.std_ == 0] = 1.0
        return self

    def _forward_log(self, X):
        Xt = X.copy()
        if self.log_mask_.any():
            Xt[:, self.log_mask_] = np.log10(np.maximum(X[:, self.log_mask_], _EPS))
        return Xt

    def transform(self, X):
        X = np.asarray(X, dtype=float)
        return (self._forward_log(X) - self.mean_) / self.std_

    def inverse_transform(self, X):
        X = np.asarray(X, dtype=float)
        Xt = X * self.std_ + self.mean_
        Xo = Xt.copy()
        if self.log_mask_.any():
            Xo[:, self.log_mask_] = np.power(10.0, Xt[:, self.log_mask_])
        return Xo


PKL_PATH = r"G:\My Drive\NEU\research\research\Buble paper\Results\8- GUI\gradboost_bundle.pkl"

# Optional friendlier labels for known outputs; anything not listed here just
# falls back to its raw column name. Names/units confirmed from the actual
# dataset and from the user; kL_detach, dNb_detach, Aint_end, AdCInt are
# still unconfirmed and intentionally left out (so they show their raw
# column name) until their definitions/units are provided.
LABEL_MAP = {
    't_detach': 'Detachment time, t<sub>d</sub> (ms)',
    'Vbubble_detach': 'Bubble volume at detachment, V (m³)',
    'Vbubble_end': 'Bubble volume at end, V (m³)',
    'yCent_detach': 'Normalized centroid height at detachment (y<sub>c</sub>/H)',
    'yCent_end': 'Normalized centroid height at end (y<sub>c</sub>/H)',
    'jNorm_detach': 'Normalized current density at detachment (j\u0305)',
    'jNorm_end': 'Normalized current density at end (j\u0305)',
    'jNorm_mean': 'Time-averaged normalized current density (j\u0305)',
    'dC_detach': 'ΔC at detachment (mol/m³)',
    'dC_end': 'ΔC at end (mol/m³)',
    'mGrowth_detach': 'Growth rate at detachment (kg/s)',
    'mGrowth_end': 'Growth rate at end (kg/s)',
    'mGrowth_mean': 'Time-averaged growth rate (kg/s)',
}

# Confidence tiers, based on leverage / h* (the applicability-domain ratio):
#   ratio <= 1.0                -> High   (inside the training domain)
#   1.0 < ratio <= MEDIUM_LIMIT -> Medium (moderately outside)
#   ratio > MEDIUM_LIMIT        -> Low    (well outside / extrapolating)
MEDIUM_RATIO_LIMIT = 2.0


def pretty_label(col_name):
    return LABEL_MAP.get(col_name, col_name)


# Display-only label overrides. E and d are the NORMALIZED (dimensionless)
# forms of those quantities, not the raw physical values -- shown with an
# overline (E̅, d̅), the standard notation for a normalized/mean quantity.
# The underlying column names ('E', 'd') used for the model are unaffected.
INPUT_LABEL_OVERRIDES = {
    'E': 'E\u0305',
    'd': 'd\u0305',
}


def input_label(feat):
    return INPUT_LABEL_OVERRIDES.get(feat, feat)


# ══════════════════════════════════════════════════════════════════════════
# Bundle loading
# ══════════════════════════════════════════════════════════════════════════
@st.cache_resource(show_spinner="Loading model…")
def load_bundle(path):
    with open(path, 'rb') as f:
        return pickle.load(f)


# ══════════════════════════════════════════════════════════════════════════
# Applicability-domain (Williams-plot-style leverage) helpers
# ══════════════════════════════════════════════════════════════════════════
def add_intercept(A):
    return np.hstack([np.ones((A.shape[0], 1)), A])


def compute_new_point_leverage(new_row_df, xscaler, input_cols, ad):
    x_scaled = xscaler.transform(new_row_df[input_cols].values)
    x_design = add_intercept(x_scaled)
    h = float((x_design @ ad['XtX_inv'] @ x_design.T)[0, 0])
    return h


def confidence_tier(h, h_star):
    ratio = h / h_star if h_star > 0 else float('inf')
    if ratio <= 1.0:
        return "High", ratio
    elif ratio <= MEDIUM_RATIO_LIMIT:
        return "Medium", ratio
    else:
        return "Low", ratio


def out_of_range_inputs(new_inputs, ranges):
    return [c for c, val in new_inputs.items()
            if not (ranges[c][0] <= val <= ranges[c][1])]


# ══════════════════════════════════════════════════════════════════════════
# Page setup
# ══════════════════════════════════════════════════════════════════════════
st.set_page_config(
    page_title="Bubble Dynamics Predictor",
    page_icon="🫧",
    layout="wide",
)

try:
    bundle = load_bundle(PKL_PATH)
except FileNotFoundError:
    st.error(f"**Model bundle not found:** `{PKL_PATH}` — run `export_gradboost_pkl.py` first.")
    st.stop()

model = bundle['model']
ad = bundle['applicability_domain']
input_cols = bundle['input_cols']
target_cols = bundle['target_cols']
xscaler = model.named_steps['xscaler']

# ══════════════════════════════════════════════════════════════════════════
# Sidebar — basic model info
# ══════════════════════════════════════════════════════════════════════════
with st.sidebar:
    st.markdown("## 🫧 Bubble Dynamics")
    st.markdown("Bubble dynamics ML-based surrogate model.")
    st.markdown("---")
    st.markdown("### Applicability domain")
    st.markdown(f"h* = `{ad['h_star']:.4f}`")
    st.markdown(f"Training rows: `{ad['n_train']}`")
    st.markdown("---")
    st.markdown("### Inputs")
    st.markdown(
        "- **Bo** — Bond number (buoyancy vs. surface tension)\n"
        "- **Mo** — Morton number (fluid property group: viscosity, "
        "density, surface tension)\n"
        "- **Sc** — Schmidt number (momentum vs. mass diffusivity)\n"
        "- **Ē** — normalized applied potential (voltage)\n"
        "- **d̄** — normalized bubble diameter (to domain height)"
    )

# ══════════════════════════════════════════════════════════════════════════
# Main — input form
# ══════════════════════════════════════════════════════════════════════════
st.title("🫧 Hydrogen Bubble Dynamics Predictor")
st.caption("An ML-based surrogate model for a single hydrogen bubble "
           "detaching from an electrode, with an applicability-domain "
           "reliability check.")

st.markdown("### Inputs")
input_vals = {}
cols = st.columns(len(input_cols))

for col_obj, feat in zip(cols, input_cols):
    lo, hi = ad['ranges'][feat]
    default = (lo + hi) / 2
    # Mo (and anything else spanning many orders of magnitude) needs
    # scientific-notation formatting to stay usable in a plain number input.
    fmt = "%.6e" if (hi / lo if lo > 0 else 0) > 1000 else "%.4f"
    with col_obj:
        val = st.number_input(
            input_label(feat), value=float(default), format=fmt, key=f'inp_{feat}',
            help=f"Training range: {lo:.4g} to {hi:.4g}",
        )
        input_vals[feat] = val

predict_clicked = st.button("⚡ Predict", use_container_width=True)

# ══════════════════════════════════════════════════════════════════════════
# Predict + reliability
# ══════════════════════════════════════════════════════════════════════════
if predict_clicked:
    row = pd.DataFrame([input_vals])[input_cols]

    preds = model.predict(row)[0]
    h = compute_new_point_leverage(row, xscaler, input_cols, ad)
    tier, ratio = confidence_tier(h, ad['h_star'])
    oor = out_of_range_inputs(input_vals, ad['ranges'])

    st.markdown("### Predictions")

    pred_by_name = dict(zip(target_cols, preds))

    if 't_detach' in pred_by_name:
        t_detach_ms = pred_by_name['t_detach'] * 1000.0  # model outputs seconds; display in ms
        st.markdown(
            f"<div style='text-align:center; margin: 8px 0 20px 0;'>"
            f"<div style='font-size:16px; font-weight:600; color:#888;'>"
            f"{pretty_label('t_detach')}</div>"
            f"<div style='font-size:48px; font-weight:800;'>"
            f"{t_detach_ms:.4g}</div>"
            f"</div>",
            unsafe_allow_html=True,
        )

    table_targets = [c for c in target_cols if c != 't_detach']

    # A plain st.dataframe renders <sub>/other HTML as literal text, not
    # actual formatting -- so this is a small hand-built HTML table instead,
    # letting labels like "y<sub>c</sub>/H" render with a real subscript.
    rows_html = "".join(
        f"<tr><td style='padding:6px 10px; border-bottom:1px solid rgba(128,128,128,0.25);'>"
        f"{pretty_label(n)}</td>"
        f"<td style='padding:6px 10px; border-bottom:1px solid rgba(128,128,128,0.25); "
        f"text-align:right;'>{pred_by_name[n]:.4g}</td></tr>"
        for n in table_targets
    )
    st.markdown(
        f"<table style='width:100%; border-collapse:collapse;'>"
        f"<thead><tr>"
        f"<th style='text-align:left; padding:6px 10px; border-bottom:2px solid rgba(128,128,128,0.4);'>Output</th>"
        f"<th style='text-align:right; padding:6px 10px; border-bottom:2px solid rgba(128,128,128,0.4);'>Value</th>"
        f"</tr></thead><tbody>{rows_html}</tbody></table>",
        unsafe_allow_html=True,
    )

    st.markdown("### Reliability")
    tier_display = {
        "High": ("✅", "success"),
        "Medium": ("⚠️", "warning"),
        "Low": ("❌", "error"),
    }
    icon, kind = tier_display[tier]
    message = (
        f"{icon} **{tier} confidence** — leverage = {h:.4f}, "
        f"h* = {ad['h_star']:.4f}  (ratio = {ratio:.2f})"
    )
    getattr(st, kind)(message)

    if oor:
        st.info(
            "Note: these inputs fall outside their individual training "
            f"ranges too: {', '.join(oor)}"
        )